name: Update Records

on:
  schedule:
    - cron: "30 1 * * 3" 
  workflow_dispatch: # Allows manual triggering from GitHub UI

permissions:
  contents: write # Allows committing changes to the repo

jobs:
  update-competitions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use a stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run the update script
        run: node src/lib/tasks/update_records.js

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add src/lib/data/records.json
          git commit -m "Update records.json"
          git push